def function_with_error: [range(10000)] | error("This is a bad function");