def function_with_error: error("This is a bad function");